### PR TITLE
Detailed listing 13

### LINKED ISSUE #13: Detailed listing of items
Show the items in a list in a detailed and organized manner for easy readability

### PR DESCRIPTION
**Pull request by Inumedia**
Fixes #13 

Implements some styling for the item listing

### CODE REVIEW

**Comment by crr** [comment]
:+1:

**Comment by crr** [comment]
The **"Icon"** column should be removed, and combined with the **"Item Name"** column, and have that be renamed to just _Item_

**Comment by crr** [comment]
LGTM! :+1:

**Comment by Inumedia** [comment]
Fixed #13

**Pull request merged**
